"""
Text preprocessing for RAG pipeline — Phase 3 addition.

Why preprocessing matters:
- The embedding model and PostgreSQL BM25 (ts_rank) both operate on raw text.
  We cannot control how BGE-M3 represents tokens internally, but we CAN control
  what text reaches the model and the FTS index.
- Vietnamese text is especially sensitive to Unicode normalization: composed vs
  decomposed diacritics (NFC vs NFD) produce different byte sequences, which
  can silently break BM25 token matching even when the words look identical.

Two separate entry-points:
  preprocess_query()    — query → query'  (called per user request)
  preprocess_document() — content field   (called at ingestion time)

Both share the same core normalize_text() function.
"""

import re
import unicodedata


def normalize_text(text: str) -> str:
    """
    Core normalization shared by both query and document paths.

    Steps
    -----
    1. Unicode NFC: compose diacritics (CRITICAL for Vietnamese).
       "a\u0300" (a + combining grave) → "à" (single codepoint).
       Without this, BM25 may fail to match user-typed vs DB-stored text.
    2. Strip leading/trailing whitespace.
    3. Collapse internal whitespace sequences to a single space.
       (Handles \\t, \\r, multiple spaces from copy-paste noise.)
    """
    if not text:
        return text

    # Step 1 — Unicode NFC composition
    text = unicodedata.normalize("NFC", text)

    # Step 2 — Strip edges
    text = text.strip()

    # Step 3 — Collapse internal whitespace
    text = re.sub(r"\s+", " ", text)

    return text


def preprocess_query(query: str) -> str:
    """
    Normalize a user query before embedding and BM25 lookup.

    Additional steps on top of normalize_text():
    - Collapse repeated punctuation (e.g. "???" → "?", "!!!" → "!")
      These contribute nothing to ts_rank and inflate token noise.
    - Do NOT strip all punctuation — some is meaningful (e.g. "10,000 đ").
    - Do NOT lowercase here — plainto_tsquery('pg_catalog.simple', ...)
      lowercases internally, and BGE-M3 is case-aware for proper nouns.

    Returns the processed query string (query').
    """
    query = normalize_text(query)
    if not query:
        return query

    # Collapse repeated punctuation marks
    query = re.sub(r"([?!.]){2,}", r"\1", query)

    return query


def preprocess_document(text: str) -> str:
    """
    Normalize user-provided document content before indexing.

    Applied to free-text fields produced by users (note, journal content,
    mood note) — NOT to the structured template lines generated by the
    formatters (those are already clean ASCII/Vietnamese).

    Keeps all content intact; only removes invisible noise that degrades
    embedding quality and FTS indexing.
    """
    return normalize_text(text)
